config/routes.rb
Rails.application.routes.draw do
  get "/admin" => "admin#index", :as => 'admin'
  get 'admin/user_data'
  get 'admin/user_new'
  post 'admin/user_create'
  get 'admin/user_edit'
  put 'admin/user_update'
  delete 'admin/user_destroy'
  get 'admin/posts'
  get 'admin/post_new'
  post 'admin/post_create'
  get 'admin/post_edit'
  put 'admin/post_update'

  resources :pages
  devise_for :users, path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'secret',
      confirmation: 'verification',
      unlock: 'unblock',
      sign_up: 'register'
  }

  resources :links
  resources :comments
  resources :categories
  resources :posts
  resources :images
  get 'welcomes/home'
  get 'welcomes/contact'
  root 'welcomes#home'
  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

end

app/views/admin/_logout.html.erb
<% if @l == :fr %>
<div class="message-box animated fadeIn" data-sound="alert" id="mb-signout">
            <div class="mb-container">
                <div class="mb-middle">
                    <div class="mb-title"><span class="fa fa-sign-out"></span> Log <strong>Out</strong> ?</div>
                    <div class="mb-content">
                        <p>Êtes-vous sûr de vouloir vous déconnecter?</p>                    
                        <p>
Appuyez sur Non si vous souhaitez continuer à travailler . Appuyez sur Oui pour déconnecter l'utilisateur actuel.</p>
                    </div>
                    <div class="mb-footer">
                        <div class="pull-right">
                            <%=link_to "Oui", destroy_user_session_path, method: :delete, class: "btn btn-success btn-lg" %>
                            <button class="btn btn-default btn-lg mb-control-close">non</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
<% else %>
<div class="message-box animated fadeIn" data-sound="alert" id="mb-signout">
            <div class="mb-container">
                <div class="mb-middle">
                    <div class="mb-title"><span class="fa fa-sign-out"></span> Log <strong>Out</strong> ?</div>
                    <div class="mb-content">
                        <p>هل أنت متأكد أنك تريد تسجيل الخروج ؟</p>                    
                        <p>اضغط لا إذا كنت ترغب في الاستمرار في العمل. اضغط نعم ل خروج المستخدم الحالي .</p>
                    </div>
                    <div class="mb-footer">
                        <div class="pull-right">
                            <%=link_to "نعم فعلا", destroy_user_session_path, method: :delete, class: "btn btn-success btn-lg" %>
                            <button class="btn btn-default btn-lg mb-control-close">لا</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

<% end %>

app/views/admin/index.html.erb
 <!-- START PAGE CONTAINER -->

 <%= stylesheet_link_tag 'admin', media: 'all' %>
 <%= csrf_meta_tags %>

  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
  <% if @l == :fr %>
  <% flash.each do |name,msg|%>
				<%= content_tag :div, msg, class: "alert alert-danger flash-popup", role: "alert" %>
				<% end %>
        <div class="page-container">
            
            <!-- START PAGE SIDEBAR -->
            <%= render 'layouts/navbar' %>
            <!-- PAGE CONTENT -->
            <div class="page-content">
                
                <!-- START X-NAVIGATION VERTICAL -->
                <ul class="x-navigation x-navigation-horizontal x-navigation-panel">
                    <!-- TOGGLE NAVIGATION -->
                    <li class="xn-icon-button">
                        <a href="#" class="x-navigation-minimize"><span class="fa fa-dedent"></span></a>
                    </li>
                    <!-- END TOGGLE NAVIGATION -->
                    <!-- SEARCH -->
                      
                    <!-- END SEARCH -->
                    <div class="info col-md-2 col-sm-2 col-md-offset-8">
          <ul class="menu-top navbar-right hidden-xs">
            <li class="divider"><%= link_to t('menu.languages.fr'), change_locale_path(:fr) %></li>
            <li ><%= link_to t('menu.languages.ar'), change_locale_path(:ar) %></li>
          </ul><!--//menu-top-->
          <br/>

        </div>
                    <!-- SIGN OUT -->

                    <li class="xn-icon-button pull-right">
                        <a href="#" class="mb-control" data-box="#mb-signout"><span class="fa fa-sign-out"></span></a>
                                                
                    </li> 

                    <!-- END SIGN OUT -->
                    <!-- MESSAGES -->
                   
                    <!-- END MESSAGES -->
                    <!-- TASKS -->
                    
                    <!-- END TASKS -->
                </ul>
                <!-- END X-NAVIGATION VERTICAL -->                     

                <!-- START BREADCRUMB -->
                <ul class="breadcrumb">
                    <li><%= link_to "domicile", admin_path %></li>                    
                    <li class="active">Tableau de bord</li>
                </ul>
                <!-- END BREADCRUMB -->  
                <div class="page-content-wrap">
                 <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default">
                        <div class="row">
                        <% if current_user.user_type == "superAdmin" %>
                        <div class="col-md-4">
                            
                            <!-- START WIDGET MESSAGES -->
                            <div class="widget widget-default widget-item-icon" onclick="location.href='<%= admin_user_data_path %>';">
                                <div class="widget-item-left">
                                    <span class="fa fa-user"></span>
                                </div>                             
                                <div class="widget-data">
                                    <div class="widget-int num-count"><%= @users_count %></div>
                                    <div class="widget-title">utilisateurs</div>
                                </div>      
                                <div class="widget-controls">                                
                                    <a href="#" class="widget-control-right widget-remove" data-toggle="tooltip" data-placement="top" title="Remove Widget"><span class="fa fa-times"></span></a>
                                </div>
                            </div>                            
                            <!-- END WIDGET MESSAGES -->
                            
                        </div>
                        <% end %>
                        <div class="col-md-4">
                            
                            <!-- START WIDGET MESSAGES -->
                            <div class="widget widget-default widget-item-icon" onclick="location.href='<%= admin_posts_path %>';">
                                <div class="widget-item-left">
                                    <span class="fa fa-file"></span>
                                </div>                             
                                <div class="widget-data">
                                    <div class="widget-int num-count"><%= @posts_count  %></div>
                                    <div class="widget-title">des postes</div>
                                </div>      
                                <div class="widget-controls">                                
                                    <a href="#" class="widget-control-right widget-remove" data-toggle="tooltip" data-placement="top" title="Remove Widget"><span class="fa fa-times"></span></a>
                                </div>
                            </div>                            
                            <!-- END WIDGET MESSAGES -->
                            
                        </div>
                        
                            
                        </div>
                       </div>
                    </div>
                 </div>
                </div>                   
             </div>
             </div>

                   
                   
               

        <!-- MESSAGE BOX-->
        <%= render 'logout' %>
        <% else %>
        <% flash.each do |name,msg|%>
                <%= content_tag :div, msg, class: "alert alert-danger flash-popup", role: "alert" %>
                <% end %>
        <div class="page-container">
            
            <!-- START PAGE SIDEBAR -->
            <%= render 'layouts/navbar' %>
            <!-- PAGE CONTENT -->
            <div class="page-content">
                
                <!-- START X-NAVIGATION VERTICAL -->
                <ul class="x-navigation x-navigation-horizontal x-navigation-panel">
                    <!-- TOGGLE NAVIGATION -->
                    <li class="xn-icon-button">
                        <a href="#" class="x-navigation-minimize"><span class="fa fa-dedent"></span></a>
                    </li>
                    <!-- END TOGGLE NAVIGATION -->
                    <!-- SEARCH -->
                      
                    <!-- END SEARCH -->
                    <div class="info col-md-2 col-sm-2 col-md-offset-8">
          <ul class="menu-top navbar-right hidden-xs">
            <li class="divider"><%= link_to t('menu.languages.fr'), change_locale_path(:fr) %></li>
            <li ><%= link_to t('menu.languages.ar'), change_locale_path(:ar) %></li>
          </ul><!--//menu-top-->
          <br/>

        </div>
                    <!-- SIGN OUT -->

                    <li class="xn-icon-button pull-right">
                        <a href="#" class="mb-control" data-box="#mb-signout"><span class="fa fa-sign-out"></span></a>
                                                
                    </li> 

                    <!-- END SIGN OUT -->
                    <!-- MESSAGES -->
                   
                    <!-- END MESSAGES -->
                    <!-- TASKS -->
                    
                    <!-- END TASKS -->
                </ul>
                <!-- END X-NAVIGATION VERTICAL -->                     

                <!-- START BREADCRUMB -->
                <ul class="breadcrumb">
                    <li><%= link_to "الصفحة الرئيسية", admin_path %></li>                    
                    <li class="active">لوحة القيادة</li>
                </ul>
                <!-- END BREADCRUMB -->  
                <div class="page-content-wrap">
                 <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default">
                        <div class="row">
                        <% if current_user.user_type == "superAdmin" %>
                        <div class="col-md-4">
                            
                            <!-- START WIDGET MESSAGES -->
                            <div class="widget widget-default widget-item-icon" onclick="location.href='<%= admin_user_data_path %>';">
                                <div class="widget-item-left">
                                    <span class="fa fa-user"></span>
                                </div>                             
                                <div class="widget-data">
                                    <div class="widget-int num-count"><%= @users_count %></div>
                                    <div class="widget-title">المستخدمي</div>
                                </div>      
                                <div class="widget-controls">                                
                                    <a href="#" class="widget-control-right widget-remove" data-toggle="tooltip" data-placement="top" title="Remove Widget"><span class="fa fa-times"></span></a>
                                </div>
                            </div>                            
                            <!-- END WIDGET MESSAGES -->
                            
                        </div>
                        <% end %>
                        <div class="col-md-4">
                            
                            <!-- START WIDGET MESSAGES -->
                            <div class="widget widget-default widget-item-icon" onclick="location.href='<%= admin_posts_path %>';">
                                <div class="widget-item-left">
                                    <span class="fa fa-file"></span>
                                </div>                             
                                <div class="widget-data">
                                    <div class="widget-int num-count"><%= @posts_count  %></div>
                                    <div class="widget-title">المشاركات</div>
                                </div>      
                                <div class="widget-controls">                                
                                    <a href="#" class="widget-control-right widget-remove" data-toggle="tooltip" data-placement="top" title="Remove Widget"><span class="fa fa-times"></span></a>
                                </div>
                            </div>                            
                            <!-- END WIDGET MESSAGES -->
                            
                        </div>
                        
                            
                        </div>
                       </div>
                    </div>
                 </div>
                </div>                   
             </div>
             </div>

                   
                   
               

        <!-- MESSAGE BOX-->
        <%= render 'logout' %>
        <% end %>
        <%= javascript_include_tag 'admin' %>

app/views/admin/user_data.html.erb
 <!-- START PAGE CONTAINER -->
 <%= stylesheet_link_tag 'admin', media: 'all' %>
 <%= csrf_meta_tags %>

  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
  <% if @l == :fr %>
  <% flash.each do |name,msg|%>
                <%= content_tag :div, msg, class: "alert alert-danger flash-popup", role: "alert" %>
                <% end %>
        <div class="page-container">
            
            <!-- START PAGE SIDEBAR -->
            <%= render 'layouts/navbar' %>
            <!-- PAGE CONTENT -->
            <div class="page-content">
                
                <!-- START X-NAVIGATION VERTICAL -->
                <ul class="x-navigation x-navigation-horizontal x-navigation-panel">
                    <!-- TOGGLE NAVIGATION -->
                    <li class="xn-icon-button">
                        <a href="#" class="x-navigation-minimize"><span class="fa fa-dedent"></span></a>
                    </li>
                    <!-- END TOGGLE NAVIGATION -->
                    <!-- SEARCH -->
                      <div class="info col-md-2 col-sm-2 col-md-offset-8">
          <ul class="menu-top navbar-right hidden-xs">
            <li class="divider"><%= link_to t('menu.languages.fr'), change_locale_path(:fr) %></li>
            <li ><%= link_to t('menu.languages.ar'), change_locale_path(:ar) %></li>
          </ul><!--//menu-top-->
          <br/>

        </div>
                    <!-- END SEARCH -->
                    <!-- SIGN OUT -->
                    <li class="xn-icon-button pull-right">
                        <a href="#" class="mb-control" data-box="#mb-signout"><span class="fa fa-sign-out"></span></a>
                                                
                    </li> 
                    <!-- END SIGN OUT -->
                    <!-- MESSAGES -->
                   
                    <!-- END MESSAGES -->
                    <!-- TASKS -->
                    
                    <!-- END TASKS -->
                </ul>
                <!-- END X-NAVIGATION VERTICAL -->                     

                <!-- START BREADCRUMB -->
                <ul class="breadcrumb">
                    <li><%= link_to "domicile", admin_path %></li>                    
                    <li class="active">UTILISATEURS</li>
                </ul>
                <!-- END BREADCRUMB -->  
                <div class="page-content-wrap">
                 <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default">
                        <div class="panel-heading">
                                    <h3 class="panel-title">UTILISATEURS</h3>
                                    <div class="btn-group pull-right">
                                    <%= link_to "Ajouter un utilisateur",admin_user_new_path, class: "btn btn-primary" %>
                                    
                                   
                                   
                                        
                                    </div>                                    
                                    
                                </div>
                                <div class="panel-body">
                                    <table id="customers2" class="table datatable">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                
                                                <th>EMAIL</th>
                                                <th>TYPE</th>
                                                <th>ACTION</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <% @users.each do |user| %>
                                            <tr>
                                                <td><%= user.id %></td>
                                                <td><%= user.email %></td>
                                                <td><%= user.user_type %></td>
                            <td> <%= link_to admin_user_edit_path(id: user.id), class: "btn btn-default btn-rounded btn-sm" do %>
                            <span class="fa fa-pencil"></span>
                            <% end %>
                            <%= link_to admin_user_destroy_path(id: user.id), method: :delete,data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-rounded btn-sm" do %>
                            <span class="fa fa-times"></span>
                            <% end %>
                            </td>
                                            </tr>
                                            <% end %>
                                            
                                </tbody>
                                    </table>                                    
                                    
                                </div>
                        </div>
                    </div>
                 </div>
                </div>                   
             </div>
             </div>

                   
                   
               

        <!-- MESSAGE BOX-->
        <%= render 'logout' %>
        <% else %>
        <% flash.each do |name,msg|%>
                <%= content_tag :div, msg, class: "alert alert-danger flash-popup", role: "alert" %>
                <% end %>
        <div class="page-container">
            
            <!-- START PAGE SIDEBAR -->
            <%= render 'layouts/navbar' %>
            <!-- PAGE CONTENT -->
            <div class="page-content">
                
                <!-- START X-NAVIGATION VERTICAL -->
                <ul class="x-navigation x-navigation-horizontal x-navigation-panel">
                    <!-- TOGGLE NAVIGATION -->
                    <li class="xn-icon-button">
                        <a href="#" class="x-navigation-minimize"><span class="fa fa-dedent"></span></a>
                    </li>
                    <!-- END TOGGLE NAVIGATION -->
                    <!-- SEARCH -->
                      <div class="info col-md-2 col-sm-2 col-md-offset-8">
          <ul class="menu-top navbar-right hidden-xs">
            <li class="divider"><%= link_to t('menu.languages.fr'), change_locale_path(:fr) %></li>
            <li ><%= link_to t('menu.languages.ar'), change_locale_path(:ar) %></li>
          </ul><!--//menu-top-->
          <br/>

        </div>
                    <!-- END SEARCH -->
                    <!-- SIGN OUT -->
                    <li class="xn-icon-button pull-right">
                        <a href="#" class="mb-control" data-box="#mb-signout"><span class="fa fa-sign-out"></span></a>
                                                
                    </li> 
                    <!-- END SIGN OUT -->
                    <!-- MESSAGES -->
                   
                    <!-- END MESSAGES -->
                    <!-- TASKS -->
                    
                    <!-- END TASKS -->
                </ul>
                <!-- END X-NAVIGATION VERTICAL -->                     

                <!-- START BREADCRUMB -->
                <ul class="breadcrumb">
                    <li><%= link_to "الصفحة الرئيسية", admin_path %></li>                    
                    <li class="active">المستخدمين</li>
                </ul>
                <!-- END BREADCRUMB -->  
                <div class="page-content-wrap">
                 <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default">
                        <div class="panel-heading">
                                    <h3 class="panel-title">المستخدمين</h3>
                                    <div class="btn-group pull-right">
                                    <%= link_to "إضافة مستخدم",admin_user_new_path, class: "btn btn-primary" %>
                                    
                                   
                                   
                                        
                                    </div>                                    
                                    
                                </div>
                                <div class="panel-body">
                                    <table id="customers2" class="table datatable">
                                        <thead>
                                            <tr>
                                                <th>هوية شخصية</th>
                                                
                                                <th>البريد الإلكتروني</th>
                                                <th>اكتب</th>
                                                <th> عمل</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <% @users.each do |user| %>
                                            <tr>
                                                <td><%= user.id %></td>
                                                <td><%= user.email %></td>
                                                <td><%= user.user_type %></td>
                            <td> <%= link_to admin_user_edit_path(id: user.id), class: "btn btn-default btn-rounded btn-sm" do %>
                            <span class="fa fa-pencil"></span>
                            <% end %>
                            <%= link_to admin_user_destroy_path(id: user.id), method: :delete,data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-rounded btn-sm" do %>
                            <span class="fa fa-times"></span>
                            <% end %>
                            </td>
                                            </tr>
                                            <% end %>
                                            
                                </tbody>
                                    </table>                                    
                                    
                                </div>
                        </div>
                    </div>
                 </div>
                </div>                   
             </div>
             </div>

                   
                   
               

        <!-- MESSAGE BOX-->
        <%= render 'logout' %>
        <% end %>
        <%= javascript_include_tag 'admin' %>