config/routes.rb
Rails.application.routes.draw do
  get "/admin" => "admin#index", :as => 'admin'
  get 'admin/user_data'
  get 'admin/user_new'
  post 'admin/user_create'
  get 'admin/user_edit'
  put 'admin/user_update'
  delete 'admin/user_destroy'
  get 'admin/posts'
  get 'admin/post_new'
  post 'admin/post_create'
  get 'admin/post_edit'
  put 'admin/post_update'

  resources :pages
  devise_for :users, path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'secret',
      confirmation: 'verification',
      unlock: 'unblock',
      sign_up: 'register'
  }

  resources :links
  resources :comments
  resources :categories
  resources :posts
  resources :images
  get 'welcomes/home'
  get 'welcomes/contact'
  root 'welcomes#home'
  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

end

app/views/layouts/_footer.html.erb
<% if @l == :fr %>
    <!-- ******FOOTER****** -->
    <footer class="footer">
      <div class="footer-content">
        <div class="container">
          <div class="row">
            <div class="footer-col col-md-3 col-sm-4 about">
              <div class="footer-col-inner">
                <h3>About</h3>
                <ul>
                  <li><a href="#"><i class="fa fa-caret-right"></i>About us</a></li>
                  <li><a href="#"><i class="fa fa-caret-right"></i>Contact us</a></li>
                  <li><a href="#"><i class="fa fa-caret-right"></i>Privacy policy</a></li>
                  <li><a href="#"><i class="fa fa-caret-right"></i>Terms & Conditions</a></li>
                </ul>
              </div><!--//footer-col-inner-->
            </div><!--//foooter-col-->
            <div class="footer-col col-md-6 col-sm-8 newsletter">
              <div class="footer-col-inner text-center">
                <h3>Joignez-vous à notre liste d'envoi</h3>

                <p>Abonnez-vous pour obtenir notre newsletter hebdomadaire livré directement à votre boîte de
                  réception</p>

                <form class="subscribe-form">
                  <div class="form-group">
                    <input type="email" class="form-control" placeholder="Enter your email"/>
                  </div>
                  <input class="btn btn-theme btn-subscribe" type="submit" value="Subscribe">
                </form>

              </div><!--//footer-col-inner-->
            </div><!--//foooter-col-->
            <div class="footer-col col-md-3 col-sm-12 contact">
              <div class="footer-col-inner">
                <h3>Contactez nous</h3>

                <div class="row">
                  <p class="adr clearfix col-md-12 col-sm-4">
                    <i class="fa fa-map-marker pull-left"></i>
                                <span class="adr-group pull-left">
                                    <span class="street-address">Universite du sahel</span><br>
                                    <span class="region">Hamdalaye A.C.I 2000</span><br>
                                    <span class="postal-code">Rue 365 Porte 71</span><br>
                                    <span class="country-name">ML</span>
                                </span>
                  </p>

                  <p class="tel col-md-12 col-sm-4"><i class="fa fa-phone"></i>(00223) 20 22 06 45</p>

                  <p class="email col-md-12 col-sm-4">
                    <i class="fa fa-envelope"></i><a href="#">universitesahel@gmail.com</a></p>
                </div>
              </div><!--//footer-col-inner-->
            </div><!--//foooter-col-->
          </div>
        </div>
      </div><!--//footer-content-->
      <div class="bottom-bar">
        <div class="container">
          <div class="row">
            <small class="copyright col-md-6 col-sm-12 col-xs-12">Copyright @ 2016 UNIVERSITÉ DU SAHEL | Website by
              <a href="#">MALINUSE</a></small>
            <ul class="social pull-right col-md-6 col-sm-12 col-xs-12">
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-youtube"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
              <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
              <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
              <li><a href="#"><i class="fa fa-skype"></i></a></li>
              <li class="row-end"><a href="#"><i class="fa fa-rss"></i></a></li>
            </ul><!--//social-->
          </div><!--//row-->
        </div><!--//container-->
      </div><!--//bottom-bar-->
    </footer><!--//footer-->

    <!-- *****CONFIGURE STYLE****** -->
    <div class="config-wrapper hidden-xs">
      <div class="config-wrapper-inner">
        <a id="config-trigger" class="config-trigger" href="#"><i class="fa fa-cog"></i></a>

        <div id="config-panel" class="config-panel">
          <p>Choose Colour</p>
          <ul id="color-options" class="list-unstyled list-inline">
            <li class="default active">
              <a data-style="assets/css/styles.css" data-logo="assets/images/logo.png" href="#"></a></li>
            <li class="green">
              <a data-style="assets/css/styles-green.css" data-logo="assets/images/logo-green.png" href="#"></a></li>
            <li class="purple">
              <a data-style="assets/css/styles-purple.css" data-logo="assets/images/logo-purple.png" href="#"></a></li>
            <li class="red">
              <a data-style="assets/css/styles-red.css" data-logo="assets/images/logo-red.png" href="#"></a></li>
          </ul><!--//color-options-->
          <a id="config-close" class="close" href="#"><i class="fa fa-times-circle"></i></a>
        </div><!--//configure-panel-->
      </div><!--//config-wrapper-inner-->
    </div><!--//config-wrapper-->

<% else %>

    <!-- ******FOOTER****** -->
    <footer class="footer">
      <div class="footer-content">
        <div class="container">
          <div class="row">
            <div class="footer-col col-md-3 col-sm-4 about">
              <div class="footer-col-inner">
                <h3>حول</h3>
                <ul>
                  <li><a href="#"><i class="fa fa-caret-right"></i>About us</a></li>
                  <li><a href="#"><i class="fa fa-caret-right"></i>Contact us</a></li>
                  <li><a href="#"><i class="fa fa-caret-right"></i>Privacy policy</a></li>
                  <li><a href="#"><i class="fa fa-caret-right"></i>Terms & Conditions</a></li>
                </ul>
              </div><!--//footer-col-inner-->
            </div><!--//foooter-col-->
            <div class="footer-col col-md-6 col-sm-8 newsletter">
              <div class="footer-col-inner text-center">
                <h3>انضم لقائمتنا البريدية</h3>

                <p>الاشتراك في النشرة الإخبارية الأسبوعية تسليمها مباشرة إلى صندوق البريد الوارد</p>

                <form class="subscribe-form">
                  <div class="form-group">
                    <input type="email" class="form-control" placeholder="ادخل بريدك الإلكتروني"/>
                  </div>
                  <input class="btn btn-theme btn-subscribe" type="submit" value="الاشتراك">
                </form>

              </div><!--//footer-col-inner-->
            </div><!--//foooter-col-->
            <div class="footer-col col-md-3 col-sm-12 contact">
              <div class="footer-col-inner">
                <h3>اتصل بنا</h3>

                <div class="row">
                  <p class="adr clearfix col-md-12 col-sm-4">
                    <i class="fa fa-map-marker pull-left"></i>
                                <span class="adr-group pull-left">
                                    <span class="street-address">Universite du sahel</span><br>
                                    <span class="region">Hamdalaye A.C.I 2000</span><br>
                                    <span class="postal-code">Rue 365 Porte 71</span><br>
                                    <span class="country-name">ML</span>
                                </span>
                  </p>

                  <p class="tel col-md-12 col-sm-4"><i class="fa fa-phone"></i>(00223) 20 22 06 45</p>

                  <p class="email col-md-12 col-sm-4">
                    <i class="fa fa-envelope"></i><a href="#">universitesahel@gmail.com</a></p>
                </div>
              </div><!--//footer-col-inner-->
            </div><!--//foooter-col-->
          </div>
        </div>
      </div><!--//footer-content-->
      <div class="bottom-bar">
        <div class="container">
          <div class="row">
            <small class="copyright col-md-6 col-sm-12 col-xs-12">Copyright @ 2016 UNIVERSITÉ DU SAHEL | Website by
              <a href="#">MALINUSE</a></small>
            <ul class="social pull-right col-md-6 col-sm-12 col-xs-12">
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="https://www.facebook.com/Universit%C3%A9-du-Sahel-de-Bamako-655344637859065/" target="_blank"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-youtube"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
              <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
              <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
              <li><a href="#"><i class="fa fa-skype"></i></a></li>
              <li class="row-end"><a href="#"><i class="fa fa-rss"></i></a></li>
            </ul><!--//social-->
          </div><!--//row-->
        </div><!--//container-->
      </div><!--//bottom-bar-->
    </footer><!--//footer-->

    <!-- *****CONFIGURE STYLE****** -->
    <div class="config-wrapper hidden-xs">
      <div class="config-wrapper-inner">
        <a id="config-trigger" class="config-trigger" href="#"><i class="fa fa-cog"></i></a>

        <div id="config-panel" class="config-panel">
          <p>Choose Colour</p>
          <ul id="color-options" class="list-unstyled list-inline">
            <li class="default active">
              <a data-style="assets/css/styles.css" data-logo="assets/images/logo.png" href="#"></a></li>
            <li class="green">
              <a data-style="assets/css/styles-green.css" data-logo="assets/images/logo-green.png" href="#"></a></li>
            <li class="purple">
              <a data-style="assets/css/styles-purple.css" data-logo="assets/images/logo-purple.png" href="#"></a></li>
            <li class="red">
              <a data-style="assets/css/styles-red.css" data-logo="assets/images/logo-red.png" href="#"></a></li>
          </ul><!--//color-options-->
          <a id="config-close" class="close" href="#"><i class="fa fa-times-circle"></i></a>
        </div><!--//configure-panel-->
      </div><!--//config-wrapper-inner-->
    </div><!--//config-wrapper-->

<% end %>

app/views/layouts/_header.html.erb
<% if @l == :fr %>

    <!-- ******HEADER****** -->
    <header class="header">
      <div class="top-bar">
        <div class="container">
          <ul class="social-icons col-md-6 col-sm-6 col-xs-12 hidden-xs">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="https://www.facebook.com/Universit%C3%A9-du-Sahel-de-Bamako-655344637859065/" target="_blank"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-youtube"></i></a></li>
            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
            <li class="row-end"><a href="#"><i class="fa fa-rss"></i></a></li>
          </ul><!--//social-icons-->
          <form class="pull-right search-form" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search the site...">
            </div>
            <button type="submit" class="btn btn-theme">Go</button>
          </form>
        </div>
      </div><!--//to-bar-->
      <div class="header-main container">
        <h1 class="logo col-md-2 col-sm-2">
          <%= link_to image_tag("logo.png"), root_path %>
        </h1><!--//logo-->

        <h1 class="logo col-md-8 col-sm-8 text-center">
          UNIVERSITÉ DU SAHEL
        </h1><!--//logo-->

        <div class="info col-md-2 col-sm-2">
          <ul class="menu-top navbar-right hidden-xs">
            <li class="divider"><%= link_to t('menu.languages.fr'), change_locale_path(:fr) %></li>
            <li ><%= link_to t('menu.languages.ar'), change_locale_path(:ar) %></li>
          </ul><!--//menu-top-->
          <br/>

        </div><!--//info-->
      </div><!--//header-main-->
    </header><!--//header-->

    <!-- ******NAV****** -->
    <nav class="main-nav" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button><!--//nav-toggle-->
        </div><!--//navbar-header-->
        <div class="navbar-collapse collapse" id="navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active nav-item"><%= link_to "ACCEUIL", root_path, class: "" %></li>
            <li class="nav-item dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="0" data-close-others="false" href="#">L'UNIVERSITÉ
                <i class="fa fa-angle-down"></i></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Présentation", page_path(1) %></li>
              </ul>
            </li>


            <li class="nav-item dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="0" data-close-others="false" href="#">LA
                FORMATION <i class="fa fa-angle-down"></i></a>
              <ul class="dropdown-menu">
                <li><a href="#">Informatique</a></li>
                <li><a href="#">Arabe</a></li>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="0" data-close-others="false" href="#">Actualités
                <i class="fa fa-angle-down"></i></a>
              <ul class="dropdown-menu">
                <li><a href="<%= posts_path %>"><i class="fa fa-newspaper-o"></i> Liste d'actualités</a></li>
              </ul>
            </li>
            <li class="nav-item"><%= link_to "Contact", welcomes_contact_path %></li>
            <%if current_user.present? %>
            <li class="nav-item"><%= link_to "se déconnecter", destroy_user_session_path, method: :delete%></li>
            <% else %>
            <li class="nav-item"><%= link_to "S'identifier", new_user_session_path %></li>
            <%end%>
          </ul><!--//nav-->
        </div><!--//navabr-collapse-->
      </div><!--//container-->
    </nav><!--//main-nav-->


<% else %>

    <!-- ******HEADER****** -->
    <header class="header">
      <div class="top-bar">
        <div class="container">
          <ul class="social-icons col-md-6 col-sm-6 col-xs-12 hidden-xs">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="https://www.facebook.com/Universit%C3%A9-du-Sahel-de-Bamako-655344637859065/" target="_blank"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-youtube"></i></a></li>
            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
            <li class="row-end"><a href="#"><i class="fa fa-rss"></i></a></li>
          </ul><!--//social-icons-->
          <form class="pull-right search-form" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search the site...">
            </div>
            <button type="submit" class="btn btn-theme">Go</button>
          </form>
        </div>
      </div><!--//to-bar-->
      <div class="header-main container">
        <h1 class="logo col-md-2 col-sm-2">
          <%= link_to image_tag("logo.png"), root_path %>
        </h1><!--//logo-->

        <h1 class="logo col-md-8 col-sm-8 text-center">جامعة الساحل</h1><!--//logo-->

        <div class="info col-md-2 col-sm-2">
          <ul class="menu-top navbar-right hidden-xs">
            <li class="divider"><%= link_to t('menu.languages.fr'), change_locale_path(:fr) %></li>
            <li ><%= link_to t('menu.languages.ar'), change_locale_path(:ar) %></li>
          </ul><!--//menu-top-->
          <br/>

        </div><!--//info-->
      </div><!--//header-main-->
    </header><!--//header-->

    <!-- ******NAV****** -->
    <nav class="main-nav" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button><!--//nav-toggle-->
        </div><!--//navbar-header-->
        <div class="navbar-collapse collapse pull-right" id="navbar-collapse">
          <ul class="nav navbar-nav">


            <li class="nav-item"><%= link_to "اتصال", welcomes_contact_path %></li>


            <li class="nav-item dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="0" data-close-others="false" href="#"> <i class="fa fa-angle-down"></i> أنباء
               </a>
              <ul class="dropdown-menu">
                <li><a href="<%= posts_path %>"><i class="fa fa-newspaper-o"></i> قائمة الأخبار</a></li>
              </ul>
            </li>

            <li class="nav-item dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="0" data-close-others="false" href="#"><i class="fa fa-angle-down"></i> تدريب</a>
              <ul class="dropdown-menu">
                <li><a href="#">حاسوب</a></li>
                <li><a href="#">العربية</a></li>
              </ul>
            </li>

            <li class="nav-item dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="0" data-close-others="false" href="#"><i class="fa fa-angle-down"></i> جامعة
                </a>
              <ul class="dropdown-menu">
                <li><%= link_to "حول", page_path(1) %></li>
              </ul>
            </li>
            <li class="active nav-item"><%= link_to "الرئسيــة", root_path, class: "" %></li>
            <%if current_user.present? %>
            <li class="nav-item"><%= link_to "خروج", destroy_user_session_path, method: :delete%></li>
            <% else %>
            <li class="nav-item"><%= link_to "تسجيل الدخول", new_user_session_path %></li>
            <%end%>



          </ul><!--//nav-->
        </div><!--//navabr-collapse-->
      </div><!--//container-->
    </nav><!--//main-nav-->

<% end %>

app/views/layouts/_lang_link.html.erb
<div class="info col-md-2 col-sm-2 col-md-offset-8">
          <ul class="menu-top navbar-right hidden-xs">
            <li class="divider"><%= link_to t('menu.languages.fr'), change_locale_path(:fr) %></li>
            <li ><%= link_to t('menu.languages.ar'), change_locale_path(:ar) %></li>
          </ul><!--//menu-top-->
          <br/>

        </div>

app/views/layouts/_logo_awards.html.erb
<section class="awards">
  <div id="awards-carousel" class="awards-carousel carousel slide">
    <div class="carousel-inner">
      <div class="item active">
        <ul class="logos">
          <li class="col-md-2 col-sm-2 col-xs-4">
            <%= image_tag("awards/award1.jpg") %>
          </li>
          <li class="col-md-2 col-sm-2 col-xs-4">
            <%= image_tag("awards/award2.jpg") %>
          </li>
          <li class="col-md-2 col-sm-2 col-xs-4">
            <%= image_tag("awards/award3.jpg") %>
          </li>
          <li class="col-md-2 col-sm-2 col-xs-4">
            <%= image_tag("awards/award4.jpg") %>
          </li>
          <li class="col-md-2 col-sm-2 col-xs-4">
            <%= image_tag("awards/award5.jpg") %>
          </li>
          <li class="col-md-2 col-sm-2 col-xs-4">
            <%= image_tag("awards/award6.jpg") %>
          </li>
        </ul><!--//slides-->
      </div><!--//item-->

      <div class="item">
        <ul class="logos">
          <li class="col-md-2 col-sm-2 col-xs-4">
            <%= image_tag("awards/award7.jpg") %>
          </li>
          <li class="col-md-2 col-sm-2 col-xs-4">
            <%= image_tag("awards/award6.jpg") %>
          </li>
          <li class="col-md-2 col-sm-2 col-xs-4">
            <%= image_tag("awards/award5.jpg") %>
          </li>
          <li class="col-md-2 col-sm-2 col-xs-4">
            <%= image_tag("awards/award4.jpg") %>
          </li>
          <li class="col-md-2 col-sm-2 col-xs-4">
            <%= image_tag("awards/award3.jpg") %>
          </li>
          <li class="col-md-2 col-sm-2 col-xs-4">
            <%= image_tag("awards/award2.jpg") %>
          </li>
        </ul><!--//slides-->
      </div><!--//item-->
    </div><!--//carousel-inner-->
    <a class="left carousel-control" href="#awards-carousel" data-slide="prev">
      <i class="fa fa-angle-left"></i>
    </a>
    <a class="right carousel-control" href="#awards-carousel" data-slide="next">
      <i class="fa fa-angle-right"></i>
    </a>

  </div>
</section>

app/views/layouts/_navbar.html.erb
<title><%= full_title(yield(:title)) %></title>
<% if @l == :fr %>
<div class="page-sidebar">
                <!-- START X-NAVIGATION -->
                <ul class="x-navigation">
                    <li class="xn-logo">
                        <a  href="index.html">Aha-Rooms</a>
                        <a href="#" class="x-navigation-control"></a>
                    </li>

                    <li class="xn-profile">
                        <a href="#" class="profile-mini">
                          <img src="<%= asset_path('admin.jpg')%>"> 
                        </a>
                        <div class="profile">
                            <div class="profile-image">
                              <img src="<%= asset_path('admin.jpg')%>"> 
                            </div>
                            <div class="profile-data">
                                <div class="profile-data-name"><%= current_user.email %></div>
                                
                                <div class="profile-data-title"><%= current_user.user_type %></div>
                                
                            </div>
                            <div class="profile-controls">
                                <div class="profile-controls">
                            <%= link_to edit_user_registration_path, class: "profile-control-left" do %>
                            <span class="fa fa-info"></span>
                            <% end %>
                               
                            </div>
                            </div>
                        </div>  

                    </li>
                    
       
                    <li class="xn-title">
panneau d'administration</li>
                    <li>
                        <%= link_to admin_path do %>
                     <span class="fa fa-th-large"></span>
                     <span class="xn-text">Tableau de bord</span>
                     <% end %>               
                    </li> 
                    
                    <li>
                        <%= link_to admin_posts_path do %>
                     <span class="fa fa-file"></span>
                     <span class="xn-text">des postes</span>
                     <% end %>
                    </li>
                    <% if current_user.user_type == "superAdmin" %>
                    <li>
                        <%= link_to admin_user_data_path do %>
                     <span class="fa fa-user"></span>
                     <span class="xn-text">utilisateurs
</span>
                     <% end %>
                    </li> 
                    <% end %>
                    
                </ul>
                <!-- END X-NAVIGATION -->
            </div>
            <!-- END PAGE SIDEBAR -->
            <% else %>
            <div class="page-sidebar">
                <!-- START X-NAVIGATION -->
                <ul class="x-navigation">
                    <li class="xn-logo">
                        <a  href="index.html">Aha-Rooms</a>
                        <a href="#" class="x-navigation-control"></a>
                    </li>

                    <li class="xn-profile">
                        <a href="#" class="profile-mini">
                          <img src="<%= asset_path('admin.jpg')%>"> 
                        </a>
                        <div class="profile">
                            <div class="profile-image">
                              <img src="<%= asset_path('admin.jpg')%>"> 
                            </div>
                            <div class="profile-data">
                                <div class="profile-data-name"><%= current_user.email %></div>
                                
                                <div class="profile-data-title"><%= current_user.user_type %></div>
                                
                            </div>
                            <div class="profile-controls">
                                <div class="profile-controls">
                            <%= link_to edit_user_registration_path, class: "profile-control-left" do %>
                            <span class="fa fa-info"></span>
                            <% end %>
                               
                            </div>
                            </div>
                        </div>  

                    </li>
                    
       
                    <li class="xn-title">لوحة الادارة</li>
                    <li>
                        <%= link_to admin_path do %>
                     <span class="fa fa-th-large"></span>
                     <span class="xn-text">لوحة القيادة</span>
                     <% end %>               
                    </li> 
                    
                    <li>
                        <%= link_to admin_posts_path do %>
                     <span class="fa fa-file"></span>
                     <span class="xn-text">المشاركات
</span>
                     <% end %>
                    </li>
                    <% if current_user.user_type == "superAdmin" %>
                    <li>
                        <%= link_to admin_user_data_path do %>
                     <span class="fa fa-user"></span>
                     <span class="xn-text">المستخدمي</span>
                     <% end %>
                    </li> 
                    <% end %>
                    
                </ul>
                <!-- END X-NAVIGATION -->
            </div>
          <% end %>
            

app/views/layouts/_slider.html.erb
<div id="promo-slider" class="slider flexslider">
  <% @images.each do |image| %>
  <ul class="slides">
    <li>
      <%= image_tag(image.image.url(:slider), size: "1140x350") %>
      <p class="flex-caption">
        <span class="main" ><%= image.image_title %></span>
        <br />
        <span class="secondary clearfix" ><%= image.description %></span>
      </p>
    </li>

  </ul><!--//slides-->
  <% end %>
</div><!--//flexslider-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 8]>
<html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]>
<html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en"> <!--<![endif]-->
<head>
  <title><%= full_title(yield(:title)) %></title>
  <!-- Meta -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
  <!-- Global CSS -->


  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="home-page">
<div class="wrapper">
  <%= render 'layouts/header' %>
  <!-- ******CONTENT****** -->
  <div class="content container">
    <%= yield %>
  </div><!--//content-->
</div><!--//cols-wrapper-->
<%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/mercury.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, maximum-scale=1.0, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <title>Mercury Editor</title>
    <%= stylesheet_link_tag    'mercury' %>
    <%= javascript_include_tag 'jquery-1.7', 'mercury' %>
  </head>
  <body>
    <script type="text/javascript">
      // Set to the url that you want to save any given page to, leave null for default handling.
      var saveUrl = null;

      // Instantiate the PageEditor
      new Mercury.PageEditor(saveUrl, {
        saveStyle:  null, // 'form', or 'json' (default json)
        saveMethod: null, // 'PUT', or 'POST', (create, vs. update -- default PUT)
        visible:    true  // boolean - if the interface should start visible or not
      });
    </script>
  </body>
</html>